name: Node Security

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: npm install
      - run: npm audit --audit-level=moderate
